sudo: false
language: python
matrix:
    include:
        - python: 2.7
          dist: trusty
          sudo: false
        - python: 3.5
          dist: trusty
          sudo: false
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - TOX_ENV=py27
install: pip install tox-travis
script:
  - tox
