#! python
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


import logging
import os.path
import re
from optparse import OptionParser
from pprint   import pprint
from zipfile  import ZipFile

from compare_locales.jars import compareJars

usage = 'usage: %prog [options] language-pack reference-pack'
parser = OptionParser(usage=usage)

parser.add_option('-v', '--verbose', action='count', dest='v', default=0,
                  help='Report more detail')
parser.add_option('-q', '--quiet', action='count', dest='q', default=0,
                  help='Report less detail')

(options, args) = parser.parse_args()
if len(args) != 2:
  parser.error('language pack and reference pack required')

# log as verbose or quiet as we want, warn by default
logging.basicConfig(level=(logging.WARNING - (options.v - options.q)*10))

# we expect two jar files
if not (args[0].endswith('.jar') and args[1].endswith('.jar')):
  parser.error('Please specify two jar files to compare')

o = compareJars(*args)
print o.serialize()
