#!python
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import sys
import logging
from optparse import OptionParser
from urlparse import urlparse
import httplib
from urllib2 import urlopen

EN_US_FEED = 'http://newsrss.bbc.co.uk/rss/newsonline_world_edition/front_page/rss.xml'
FEEDSERVER = '%s.fxfeeds.mozilla.com'
FEEDPATH   = '/%s/firefox/headlines.xml'

L10NFEEDS = 'https://wiki.mozilla.org/index.php?title=Firefox/L10n_Feed_Redirects&action=raw'

op = OptionParser()
op.add_option('--oldid', dest='oldid',
              help='explicitly give a version number on the wiki')
op.add_option('-v', dest='verbose', action='count', default=0,
              help='increase verbosity')
(options, args) = op.parse_args()

if len(args) != 1:
  sys.exit('all-locales or shipped-locales path expected')

logging.basicConfig(level=(logging.WARNING - options.verbose*10))

if options.oldid:
  L10NFEEDS += '&oldid=' + options.oldid

lFeeds = urlopen(L10NFEEDS)
redirs = {}

for row in lFeeds:
  d, loc, url = row.split(' ', 2)
  redirs[loc] = url.strip()

# parse all-locales and shipped-locales, only take first bunch
lFile = open(args[0])
locales = [ln.split(' ', 1)[0].strip() for ln in lFile]
# ignore ja-JP-mac, same bookmarks as ja
def not_ja_JP_mac(loc): return loc != 'ja-JP-mac'
locales = filter(not_ja_JP_mac, locales)

for loc in locales:
  logging.debug('testing ' + loc)
  server = FEEDSERVER % loc
  path   = FEEDPATH % loc
  while server.endswith('mozilla.com'):
    url = None
    conn = httplib.HTTPConnection(server)
    conn.request('HEAD', path)
    r = conn.getresponse()
    if r.status != 302:
      logging.error('mozilla.com loses feed for ' + loc)
      server = ''
      continue
    url = r.getheader('location')
    server, path = urlparse(url)[1:3]
    conn.close()
  refurl = EN_US_FEED
  if redirs.has_key(loc):
    refurl = redirs[loc]
  if url != refurl:
    print loc, "FAIL"
    logging.info(str(url) + ' is not ' + refurl)
  else:
    logging.debug(loc + ' PASS')

